#!/usr/bin/env python

import numpy as np
from cogue.interface.vasp_io import Vasprunxml

import argparse
parser = argparse.ArgumentParser(description="Collect eigenvalues from vasprun.xml")
parser.add_argument('filenames', nargs='*')
args = parser.parse_args()

for filename in args.filenames:
    vasprun = Vasprunxml(filename=filename)
    if vasprun.parse_eigenvalues():
        eigvals = np.ravel(vasprun.get_eigenvalues())
        occupancies = np.ravel(vasprun.get_occupancies())
        indices = np.argsort(eigvals)
        prev_occ = 0
        prev_eig = 0
        band_gap = 0
        for i, (e, o) in enumerate(zip(eigvals[indices], occupancies[indices])):
            if i > 0:
                if np.abs(np.abs(prev_occ - o) - 1) < 1e-6:
                    band_gap = e - prev_eig
                    
            print "%10.5f %7.5f" % (e, o)
            prev_occ = o
            prev_eig = e

        print "# Band gap:", band_gap
