#!/usr/bin/env python

import cogue.calculator.vasp as vasp
import cogue.crystal.ui_utils as ui_utils
from cogue.crystal.converter import write_v_sim

options, args = ui_utils.get_options()
cells = [ui_utils.transform_cell(vasp.parse_poscar(filelines), options)
         for filelines in ui_utils.get_lines(args)]
ui_utils.write_cells(write_v_sim, cells, args, options.output_filename)
