#!/usr/bin/env python

import cogue.calculator.vasp as vasp
import cogue.crystal.ui_utils as ui_utils
from cogue.crystal.converter import write_cif_P1

options, args = ui_utils.get_options()
cell = ui_utils.transform_cell(vasp.read_poscar(args[0]), options)
if cell:
    print "Transformed cell is written to %s.cif" % args[0]
    write_cif_P1(cell, args[0] + ".cif")
else:
    print "Transformation failed."

