#!/usr/bin/env python

import sys
import cogue.calculator.vasp as vasp
import cogue.crystal.ui_utils as ui_utils

options, args = ui_utils.get_options()
cell = ui_utils.transform_cell(vasp.read_poscar(args[0]), options)
if cell:
    print "Transformed cell is written to %s.new" % args[0]
    vasp.write_poscar(cell, args[0] + ".new")
else:
    print "Transformation failed."
