#!/usr/bin/env python

import cogue.calculator.vasp as vasp
import cogue.crystal.ui_utils as ui_utils
from cogue.crystal.converter import write_v_sim

options, args = ui_utils.get_options()
cell = ui_utils.transform_cell(vasp.read_poscar(args[0]), options)
if cell:
    if options.output_filename:
        write_v_sim(cell, options.output_filename)
    else:
        write_v_sim(cell)
else:
    print "Transformation failed."
