#!/usr/bin/env python

import cogue.interface.ui_utils as ui_utils
import cogue.interface.vasp_io as vasp_io
from cogue.interface.cif import write_cif_P1

options, args = ui_utils.get_options()
cells = [
    ui_utils.transform_cell(vasp_io.parse_poscar(filelines), options)
    for filelines in ui_utils.get_lines(args)
]
ui_utils.write_cells(write_cif_P1, cells, args, options.output_filename)
