#!/usr/bin/env python

import cogue.interface.ui_utils as ui_utils
import cogue.interface.vasp_io as vasp_io
from cogue.interface.v_sim import write_v_sim

options, args = ui_utils.get_options()
cells = [
    ui_utils.transform_cell(vasp_io.parse_poscar(filelines), options)
    for filelines in ui_utils.get_lines(args)
]
ui_utils.write_cells(write_v_sim, cells, args, options.output_filename)
