#!/usr/bin/env python

import os
import sys
from optparse import OptionParser

import cogue.interface.vasp_io as vasp

parser = OptionParser()
parser.set_defaults(count_offset=None)
parser.add_option(
    "--offset", dest="count_offset", type="int", help="File number offset"
)
(options, args) = parser.parse_args()

if options.count_offset:
    count = 1 + options.count_offset
else:
    count = 1

for filename in args:
    if not os.path.exists(filename):
        sys.stderr.write("%s doesn't exist.\n" % filename)
        continue

    vxml = vasp.VasprunxmlExpat(filename)
    if not vxml.parse():
        sys.stderr.write("XML tag of %s is not cleanly closed.\n" % filename)
    cells = vxml.get_cells()
    for cell in cells:
        vasp.write_poscar(cell, "POSCAR-%03d" % count)
        count += 1
